#!/usr/bin/env python3
"""
inject_version.py — Single source of truth for the badge firmware version.

Reads firmware/VERSION (a one-line semver like "0.1.4") and injects:

  -DFIRMWARE_VERSION="<ver>"          (consumed by src/identity/BadgeVersion.h
                                       and any C++ TU that includes it)
  -DBADGE_FIRMWARE_VERSION="<ver>"    (consumed by lib/micropython_embed/src/
                                       mpconfigport.h to format the REPL banner
                                       "Replay Badge v<ver> with ESP32-S3")

Both header files keep their #ifndef fallbacks so direct `pio run` without
this script (or Arduino IDE builds) still compile — they just report the
hard-coded fallback string instead of the canonical VERSION.
"""

from __future__ import annotations

from pathlib import Path

try:
    Import("env")  # type: ignore[name-defined]
except NameError:
    env = None


def project_dir() -> Path:
    if env is not None:
        return Path(env.subst("$PROJECT_DIR"))
    return Path(__file__).resolve().parents[1]


def read_version(root: Path) -> str:
    path = root / "VERSION"
    if not path.exists():
        return "dev"
    raw = path.read_text(encoding="utf-8").strip()
    return raw or "dev"


def write_generated_header(root: Path, version: str) -> Path:
    """Emit a header so VERSION-only bumps invalidate incremental builds."""
    header = root / "src" / "identity" / "GeneratedFirmwareVersion.h"
    content = (
        "#pragma once\n"
        "// AUTO-GENERATED by scripts/inject_version.py — do not edit.\n"
        f'#define FIRMWARE_VERSION "{version}"\n'
        f'#define BADGE_FIRMWARE_VERSION "{version}"\n'
    )
    if header.exists() and header.read_text(encoding="utf-8") == content:
        return header
    header.parent.mkdir(parents=True, exist_ok=True)
    header.write_text(content, encoding="utf-8")
    return header


def main() -> None:
    root = project_dir()
    version = read_version(root)
    header = write_generated_header(root, version)

    print(f"[inject_version] firmware version = {version}")

    if env is None:
        return

    # Header + explicit dependency: a VERSION-only change must rebuild
    # BootSplash, DiagnosticsScreen, BadgeOTA, and the MicroPython embed.
    env.Depends("$BUILD_DIR/${PROGNAME}.elf", str(header))
    env.Depends("$BUILD_DIR/${PROGNAME}.elf", str(root / "VERSION"))


main()
